### ISSUE TITLE
Use the library SONAME as the module name when present

### ISSUE THREAD

**Issue by gabrielesvelto** [mozilla/dump_syms#110]
ELF files can have a SONAME that differs from the filename, when they do the SONAME should be used as the module name in the first line of output, like:
```
MODULE Linux x86_64 B29B5D0942181476F8BE6AD24FF571C80 libgallium_drv_video.so
```
Instead of
```
MODULE Linux x86_64 B29B5D0942181476F8BE6AD24FF571C80 nouveau_drv_video.so
```
For a filename called `nouveau_drv_video.so` in mesa, for example.

**Comment by calixteman** [comment]
I made a PR in symbolic to add the possibility to get soname (for elf) and dylib name (for macho):
https://github.com/getsentry/symbolic/pull/252

**Comment by gabrielesvelto** [comment]
This was fixed, I forgot to close it.
