### ISSUE TITLE
Some private symbols have mangled name

### ISSUE THREAD

**Issue by calixteman** [mozilla/dump_syms#14]
For example:
https://crash-stats.mozilla.com/report/index/c9864db3-ede5-4444-982b-8ad300191004

The top function is static void ??__FsConfig@gfx@mozilla@@YAXXZ().
According to https://github.com/llvm/llvm-project/blob/master/clang/lib/AST/MicrosoftMangle.cpp#L3412 we've here a dynamic atexit dtor (undname failed on this name).

The info for this symbol are:
FUNC 173b130 371 0 void ??__FsConfig@gfx@mozilla@@YAXXZ()
173b130 179 16 6066
173b2a9 1f8 16 5830

it refers to lines 16 in:
 - obj-firefox\gfx\config\Unified_cpp_gfx_config0.cpp
 - gfx\config\gfxConfig.cpp

which is pretty confusing.

**Comment by gabrielesvelto** [comment]
That corresponds to the `sConfig` global variable [here](https://searchfox.org/mozilla-central/rev/b6f088f2f68d2a8ae0b49d6c8fbd7cbd3a65fa5b/gfx/config/gfxConfig.cpp#16). Since it's static and a `UniquePtr` it will have an implicit static destructor generated by the compiler, that must be it.

**Comment by gabrielesvelto** [comment]
I've just checked this in recent builds and it's not happening anymore, closing
