### ISSUE TITLE
Compare function names in test

### ISSUE THREAD

**Issue by calixteman** [mozilla/dump_syms#17]
We need to have more options in msvc demangler to be able to have the same output:
https://github.com/getsentry/symbolic/issues/163
and then we can re-enable public symbols names comparison in test:
https://github.com/mozilla/dump_syms/blob/master/src/windows/pdb.rs#L596-L600

**Comment by mstange** [comment]
It seems like these tests were designed to compare our output to breakpad's traditional output.

Now that we're fully switched over, I think the traditional output has lost its relevance and we can just make our current output the new reference, by regenerating the reference .sym files. Then we can just equality-compare all function names in the tests.

Does that sound good?

**Comment by calixteman** [comment]
Yes it makes sense, r=me.
