### ISSUE TITLE
Panic when trying to dump symbols from a .exe file

### ISSUE THREAD

**Issue by Eijebong** [mozilla/dump_syms#220]
> 08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .text for 0x35f7000 ∈ 0x1000..0x26007e8
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .data for 0x35f7000 ∈ 0x2601000..0x26a3540
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .rdata for 0x35f7000 ∈ 0x26a4000..0x35f6c70
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .buildid for 0x35f7000 ∈ 0x35f7000..0x35f7035
08:55:04 [DEBUG] (1) goblin::pe::utils: Found in section .buildid(3), remapped into offset 0x35f6400
08:55:04 [DEBUG] (1) goblin::pe: exception data: None
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .text for 0x3634000 ∈ 0x1000..0x26007e8
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .data for 0x3634000 ∈ 0x2601000..0x26a3540
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .rdata for 0x3634000 ∈ 0x26a4000..0x35f6c70
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .buildid for 0x3634000 ∈ 0x35f7000..0x35f7035
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .qtmetadata for 0x3634000 ∈ 0x35f8000..0x35f8ae0
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .qtmimedatabase for 0x3634000 ∈ 0x35f9000..0x3634000
08:55:04 [DEBUG] (1) goblin::pe::utils: Checking .pdata for 0x3634000 ∈ 0x3634000..0x381d8e8
08:55:04 [DEBUG] (1) goblin::pe::utils: Found in section .pdata(6), remapped into offset 0x3633000
08:55:04 [ERROR] A panic occurred at src/windows/utils.rs:44: called `Option::unwrap()` on a `None` value

There is no generated pdb with that exe

**Comment by mstange** [comment]
This was fixed by #222.
