### ISSUE TITLE
Remove constant string from the symbol list

### ISSUE THREAD

**Issue by calixteman** [mozilla/dump_syms#26]
Some constant string generally mangled as "??_C..." appears as symbol function because they're in an executable section and section contributions don't contain any entries about those symbols (see in ntdll.pdb).
So we can filter them on their mangled name.

**Comment by mstange** [comment]
This was fixed by #25. https://github.com/mozilla/dump_syms/commit/dcc417cd454d3469a99894a95d2b79fa65e7f01c#diff-85c9cfdfa8ad3bb98f3bddfbfeb47f5761d6e585ed9f7003e9a54b2b4e3f1c3bR269-R271
