### ISSUE TITLE
Get symbols from .gnu_debuginfo section for files which have it (Android system libraries) (MiniDebuginfo)

### ISSUE THREAD

**Issue by mstange** [mozilla/dump_syms#307]
Many Android system libraries don't carry any regular symbols. This leaves the .sym file pretty much empty:
https://symbols.mozilla.org/libandroid.so/09A012293F4418FD4DC729E510E384D20/libandroid.so.sym

Instead, their symbol table is moved to a compressed object file which is stored in the .gnu_debugdata section. This format is described here: https://sourceware.org/gdb/onlinedocs/gdb/MiniDebugInfo.html

Getting the symbols back out is pretty easy:

 1. Get the section. `if let Some(debugdata) = object_file.section_by_name(".gnu_debugdata") {`
 2. Pull out the compressed data.
 3. Run the compressed data through `lzma_rs::xz_decompress`.
 4. Treat the outcome as a new ELF file, and dump symbols from it.

In the example libandroid.so from above, this gives 126 functions.

**Comment by gabrielesvelto** [comment]
Is this something we should do in dump_syms directly? Or would it be something that symbolic would have to deal with (or possibly gimli and then symbolic through it)?

**Comment by mstange** [comment]
I'd say either here or in symbolic, but I haven't read enough of the dump_syms code to know exactly how the responsibilities are distributed.

**Comment by calixteman** [comment]
I think it'd be pretty easy to add that to dump_syms.
It should be pretty similar to what we have for mac:
https://github.com/mozilla/dump_syms/blob/bf7f6bd855eb6ecb233b52bfa7b2c975b7026540/src/mac/macho.rs#L35-L52
just extract the data and pass them to `elf::ElfInfo`.

**Comment by calixteman** [comment]
@mstange, do you have few links to share to get some android dbg files ?

**Comment by mstange** [comment]
I do!

 - [libllvm-glnext.so](https://drive.google.com/file/d/1nzLQM8S9w2siUfNh19s6IxFHKrI5cINS/view?usp=sharing)
 - [libGLESv2_adreno.so](https://drive.google.com/file/d/1NRJqdH0F2x8u903HPyFmyt19ie_-EEsQ/view?usp=sharing)
