### ISSUE TITLE
libsystem_kernel.dylib is a mix of x64 and arm64 cfi, and we end up using the x64 instructions on arm64

### ISSUE THREAD

**Issue by Gankra** [mozilla/dump_syms#402]
(which of course fails)

https://github.com/rust-minidump/rust-minidump/issues/607#issuecomment-1176578702

https://symbols.mozilla.org/libsystem_kernel.dylib/1D7B3B8E75A134EAAA529F7C23155C550/libsystem_kernel.dylib.sym

**Comment by Gankra** [comment]
oh nope this is an upstream symbolic issue: https://github.com/getsentry/symbolic/blob/6c074ad83f1d38f8585705808b638e5b2d2ad3f9/symbolic-cfi/src/lib.rs#L552

**Comment by Gankra** [comment]
wait these symbols might just be really old, from before https://github.com/getsentry/symbolic/pull/445

**Comment by mstange** [comment]
That fix is in 9.1.0, which we have now in dump_syms, so this is fixed.
