### ISSUE TITLE
Mixed paths emitted for PDBs with Linux paths

### ISSUE THREAD

**Issue by mstange** [mozilla/dump_syms#444]
This is a regression from #433.

When dump_syms is run on a PDB file, and this PDB file contains Linux paths, then weird things happen.

```
PDB:  /builds/worker/workspace/obj-build/dist/include/nsIFile.h
.sym: /builds/worker/workspace/obj-build/dist/include\nsIFile.h
```

Normally, PDB files contain Windows paths with backslashes, so we'd want dump_syms to use backslashes for paths in PDBs even when dump_syms is run on Linux. But what if the PDB file contains Linux paths to start with?

Ideally we'd just preserve the path as originally written down in the PDB. But symbolic-debuginfo splits paths into a "compilation dir" and a "filename" component, and discards the path separator.

How should we pick the path separator to use for gluing those components back together?

**Comment by gabrielesvelto** [comment]
Can't we just use Windows separators when dealing with PDBs? Or are there cases where a PDB would contain non-Windows path separators?

**Comment by mstange** [comment]
> Can't we just use Windows separators when dealing with PDBs?

This is what we do today.

> Or are there cases where a PDB would contain non-Windows path separators?

Yes, exactly. The Firefox Windows builds are compiled on a Linux machine, so they contain Linux paths to the source files.

**Comment by gabrielesvelto** [comment]
> Yes, exactly. The Firefox Windows builds are compiled on a Linux machine, so they contain Linux paths to the source files.

Duh. I forgot about that.
