### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mstange** [mozilla/dump_syms#448]
Let's make a release which includes `--inlines` functionality.

@gabrielesvelto Can you publish dump_syms 2.0.0?

**Comment by gabrielesvelto** [comment]
Sorry for the delay here, I'm cooking up a 2.0.0 release, configuring the project with `cargo-release`. It's taking a bit because I've never used it before but hopefully it should make future releases quicker.

**Comment by gabrielesvelto** [comment]
I *think* I have everything setup correctly, pushing a new release, fingers crossed

**Comment by mstange** [comment]
Thank you! It looks like it worked: https://crates.io/crates/dump_syms

**Comment by gabrielesvelto** [comment]
I've cut the new release and everything seems OK, except that the links and versions in the changelog weren't auto-updated and I don't know why, but it's not a big deal, I'm going to fix it later.
