### ISSUE TITLE
include dump_syms version in sym file

### ISSUE THREAD

**Issue by willkg** [mozilla/dump_syms#487]
There are cases where it'd be helpful to know which version of `dump_syms` generated the sym file.

Can we include it in an `INFO` line?

**Comment by mstange** [comment]
We already have `INFO CODE_ID` and `INFO URL`, so how about `INFO GENERATOR`?

```
INFO GENERATOR dump_syms 2.0.0
```

In symbolic's breakpad parser, any `INFO` line which does not start with `INFO CODE_ID` [gets turned into `BreakpadInfoRecord::Other`](https://github.com/getsentry/symbolic/blob/master/symbolic-debuginfo/src/breakpad.rs#L1655-L1670).
In rust-minidump's parser, any `INFO` line which does not start with `INFO URL` [gets turned into `Info::Unknown`](https://github.com/rust-minidump/rust-minidump/blob/main/breakpad-symbols/src/sym_file/parser.rs#L389).

**Comment by calixteman** [comment]
@gabrielesvelto: https://github.com/mozilla-services/updatebot

**Comment by willkg** [comment]
I'm ok with using the git revision instead of a version. I just need to be able to know which specific `dump_syms` generated the sym file.

**Comment by mstange** [comment]
The version can be obtained from `env!("CARGO_PKG_VERSION")`. For the git revision, a small `build.rs` is needed, according to [this stackoverflow answer](https://stackoverflow.com/a/44407625).

**Comment by gabrielesvelto** [comment]
I went with the version number because I've automated the release flow so cutting a new release is a piece of cake and it doesn't have the ambiguity of git revisions coming from different branches.
