### ISSUE TITLE
add support for aarch64 windows unwinding information

### ISSUE THREAD

**Issue by froydnj** [mozilla/dump_syms#5]
We have a patch in [bug 1529355](https://bugzilla.mozilla.org/show_bug.cgi?id=1529355) for interpreting aarch64 unwind information and emitting the appropriate bits in breakpad symbol files.  We haven't landed it yet because clang-cl was producing bogus unwind information until clang 9...which we are just about to enable, I think?

I think I have a slightly updated patch that fixes some of the breakage that resulted from landing the patch; I'll try to get that uploaded to the bug.

**Comment by calixteman** [comment]
We should probably rewrite your patch in rust and split it:
 - one part in https://github.com/m4b/goblin/blob/master/src/pe/exception.rs to read and parse unwind code
 - and a second part in https://github.com/getsentry/symbolic/blob/master/minidump/src/cfi.rs to generate CFI informations from unwind operations got from the pe.

**Comment by gabrielesvelto** [comment]
Symbolic has had support for this for a while, and consequently we've had it in dump_syms too.
