### ISSUE TITLE
store additional metadata in INFO lines

### ISSUE THREAD

**Issue by willkg** [mozilla/dump_syms#502]
We use `dump_syms` to extract symbol information from binaries for a specific build of some product. The symbol files are then uploaded to the symbol server. At that point, we have no way of knowing which build of what product generated this symbol information. It would be helpful to capture that at the time `dump_syms` was run. This would help debugging symbol problems, indexing symbols for finding them later, etc.

Maybe there's other information that would be helpful to capture as well? Maybe it's helpful to generalize the problem to "capture additional metadata at the time of symbol file creation and store as key/value pairs in INFO lines"?

Maybe something like:

```
dump_syms --info=ProductName:Firefox --info=ReleaseChannel:nightly --info=BuildID:20221118000000 -s outputdir libxul.so
```

Which would then result in a header something like this:

```
MODULE Linux x86_64 8F91CC4320D4B79F745D18F5D50C46A30 libxul.so
INFO CODE_ID 43CC918FD4209FB7745D18F5D50C46A33009215D
INFO PRODUCTNAME Firefox
INFO RELEASECHANNEL nightly
INFO BUILDID 20221118000000
```

Or something like that.

**Comment by willkg** [comment]
Something like this would make it a lot easier to add APIs to the Mozilla Symbols Server to do things like "get all the symbols for build xyz".

**Comment by gabrielesvelto** [comment]
This is done, I just need to cut a new releases
