### ISSUE TITLE
Windows binary release?

### ISSUE THREAD

**Issue by Jimbly** [mozilla/dump_syms#505]
Hi!  I'm running into an issue with Breakpad's dump_syms not working on Windows 11, and am wondering if this project would work as a drop-in replacement.  I know nothing of Rust, but would it be possible to get a binary release that runs on Windows without needing to install a Rust toolchain to try it out?

**Comment by mstange** [comment]
@gabrielesvelto It seems like we could use a github workflow to create and upload these builds automatically whenever we make a release.

For example using https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases#example-workflow-basic-usage-multiple-platforms or https://github.com/marketplace/actions/rust-release-binary#build-windows-and-linux-and-upload-as-zip

What do you think?

**Comment by gabrielesvelto** [comment]
Sounds like a good idea and I'm happy if the tool sees more adoption. I'll try and find some time to look into those workflows in the coming days.

**Comment by Jimbly** [comment]
I can't promise I'll adopt it (I got Breakpad's working again on Win 11 after discovering it was just a missing msdia140.dll I had to copy from another system ^_^), but I'll at least try dropping it into my pipeline and see what happens if there's a Windows binary easily available =).

**Comment by gabrielesvelto** [comment]
Our version is over twice as fast and takes a quarter of the memory of Breakpad's, plus the output is both richer *and* smaller. There's too many improvements to list them all.

**Comment by gabrielesvelto** [comment]
We now have Windows binary releases.
