### ISSUE TITLE
Stop installing Nightly toolchain, just use the right Rust Docker image

### ISSUE THREAD

**Issue by marco-c** [mozilla/dump_syms#52]

**Comment by mstange** [comment]
I'm guessing this is referring to the `rustup default nightly` in the code coverage part of .taskcluster.yml:
https://github.com/mozilla/dump_syms/blob/65342cfafcecbc53a6b2d603b90a47132add0d72/.taskcluster.yml#L73

**Comment by gabrielesvelto** [comment]
This was fixed when we moved to GitHub's CI
