### ISSUE TITLE
invalid sym file: INLINE_ORIGIN missing symbol

### ISSUE THREAD

**Issue by willkg** [mozilla/dump_syms#543]
I'm seeing sym files generated with dump_syms 2.1.1 that are missing the symbol in the `INLINE_ORIGIN` lines. We've seen issues along these lines previously. I think this is a new instance.

Example (very large 650mb) file:

https://symbols.mozilla.org/try/libxul.so/5AC6F470F832952B3246C5EADF3017AA0/libxul.so.sym

This was uploaded 6 days ago:

https://symbols.mozilla.org/uploads/upload/442469

First column is the line number in the file. Line 690,455 is missing the symbol:

```
690452 INLINE_ORIGIN 671174 alloc::alloc::box_free
690453 INLINE_ORIGIN 671175 ace(const TraceCallbacks&, void*)::<lambda(auto:34&& ...)> >
690454 INLINE_ORIGIN 671176 style::gecko_properties::<impl core::ops::drop::Drop for style::gecko_bindings::structs::root::mozilla::         GeckoMargin>::drop
690455 INLINE_ORIGIN 671177  
690456 INLINE_ORIGIN 671178 style::gecko_properties::<impl core::ops::drop::Drop for style::gecko_bindings::structs::root::mozilla::         GeckoOutline>::drop
690457 INLINE_ORIGIN 671179 core::ptr::drop_in_place<alloc::boxed::Box<servo_arc::ArcInner<style::gecko_bindings::structs::root::moz         illa::GeckoPage>>>
```

It looks like maybe the symbol is a single space. Maybe this code needs to additionally check for "name consists solely of whitespace"?

https://github.com/mozilla/dump_syms/blob/2b8f4a9c269aa80f0126ea8ecfec971dcd7df50c/src/collector.rs#L400-L403

**Comment by gabrielesvelto** [comment]
It looks like it's a Fedora package again. It might be buggy debug information emitted by GCC (I don't see how a symbol could be made only of whitespace) or maybe something valid but very, very odd. Either way we need to handle it like we handle missing symbols.

**Comment by gabrielesvelto** [comment]
Here's the [task](https://firefox-ci-tc.services.mozilla.com/tasks/KApPw3XFRSaNSDQrkp-efQ) that most likely uploaded those symbols, let's see what was in the original debug info.

**Comment by gabrielesvelto** [comment]
I've managed to find the [package](http://fedora.mirror.garr.it/fedora/linux/updates/36/Everything/x86_64/Packages/f/firefox-109.0-4.fc36.x86_64.rpm) and its [debuginfo](http://fedora.mirror.garr.it/fedora/linux/updates/36/Everything/x86_64/debug/Packages/f/firefox-debuginfo-109.0-4.fc36.x86_64.rpm). I'll crack it up later today.

**Comment by gabrielesvelto** [comment]
I can reproduce the issue locally, I'll investigate it tomorrow.

**Comment by willkg** [comment]
Thank you!
