### ISSUE TITLE
Calling dump_syms on a .pdb does not produce CFI unwinding directives

### ISSUE THREAD

**Issue by gabrielesvelto** [mozilla/dump_syms#56]
I was testing the tool on my local Firefox build and I noticed that if I pass it a .pdb file to dump instead of a .dll the STACK CFI directives are not present in the output. To reproduce in a local build try this:
```
# Produces the correct output
dump_syms.exe <firefox_build>/toolkit/library/build/xul.dll > xul.sym
# STACK CFI directives are missing in the output
dump_syms.exe <firefox_build>/toolkit/library/build/xul.pdb > xul.sym
```
The old dump_syms produces the same output in both cases.

**Comment by calixteman** [comment]
https://github.com/mozilla/dump_syms/pull/57
