### ISSUE TITLE
armv8 linux builds

### ISSUE THREAD

**Issue by michxymi** [mozilla/dump_syms#684]
Hey all,

How much of an issue would be to add armv8/aarch64 linux binaries as part of the releases?

I'm trying to create a [conan package](https://github.com/conan-io/conan-center-index) so this can be integrated in C/C++ projects.

**Comment by gabrielesvelto** [comment]
We use `cargo-dist` to configure our releases and it doesn't support AArch64/Linux as a target yeah. I suspect that's because GitHub has no AArch64 Linux runners available, so while it's possible to cross-compile a build it wouldn't be possible to run the test suite.

**Comment by michxymi** [comment]
By the looks of it, `cargo-dist` supports aarch linux as a custom target but natively rather than cross-compiling. But yes, sadly the problem remains that there's a need for an actual aarch64 runner :/ See https://github.com/axodotdev/cargo-dist/issues/324

**Comment by gabrielesvelto** [comment]
I see. Well, when (or if) there will be an appropriate runner I'll add it. In the meantime you might be able to cross-compile it yourself, but chances are that you also need a C cross-compiler for some dependencies like ring.
