### ISSUE TITLE
Unnecessary "static" in demangled symbol names for static methods

### ISSUE THREAD

**Issue by mstange** [mozilla/dump_syms#77]
Context: The Firefox profiler uses the mozilla symbol server to symbolicate profiles. Our goals are to have readable and concise symbols in the profiler and we don't have any constraints when it comes to consistency with other tools.

Profile: https://perfht.ml/2K6UWY7
In this profile you can see symbol names such as `static js::ErrorObject::getStack(JSContext*, unsigned int, JS::Value*)`.
Could we lose the "static " at the beginning? It's not providing much value in the profiler.

**Comment by calixteman** [comment]
@gabrielesvelto, are you ok to remove `static` ? does the keyword matter in signature generation ?

**Comment by willkg** [comment]
Socorro's signature generation drops the prefix and return type.

Here's an example: https://crash-stats.mozilla.org/report/index/e2001321-95be-4364-ba20-732c70210126
